title: "Casey P O'Brien"
author: "Casey P O'Brien"
description: "North Carolina State University PhD Student"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
 # - {file: "archive.html", title: "Home", sidebaricon: home}
  - {file: "CV.html", title: "CV", sidebaricon: info-circle}
  - {file: "personal.md", title: "Personal Life", sidebaricon: address-card}
 # - {file: "ABOUTME.md", title: "Blog", sidebaricon: paragraph}



external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:cpobrie6@ncsu.edu"}
  - {title: Github, icon: github, url: "https://github.com/cpobrie6"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/casey-p-obrien"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
